### PR TITLE
credential saved message; fixes #33

### LINKED ISSUE #33: unexpected behaviour of the credential saved message
The issue is with the message **"Your credentials have been saved"**.

### Expected Behaviour 
The message should show up only after entering all the details. 

### Current Behaviour
The message pops up after every keypress.

### Screenshots
Screenshot from 2020-09-14 01-46-17

### PR DESCRIPTION
**Pull request by sahil-shubham**
I have made the changes so that the link to erp only pops up after all the credentials have been entered. I also changed the `reset` message as I thought it wasn't necessary to show the link to erp just after clearing all the credentials.

This would fix #33

### CODE REVIEW

**Comment by sahil-shubham** [comment]
@thealphadollar I was thinking of giving each message `(changes saved, credentials saved & credentials reset)` a different colour so that the user knows that the message changed even without reading. What do you think about this? and what colors should I choose for each message in your opinion?

**Comment by thealphadollar** [comment]
> I was thinking of giving each message (changes saved, credentials saved & credentials reset)

This is ingenious,and along with a different color, it would be awesome to even have there :D

> What do you think about this? and what colors should I choose for each message in your opinion?

Hmm, let's know what @ooyeraju has to suggest. He seems to be learning design, I'm a noob at this :monkey:

**Comment by sahil-shubham** [comment]
@thealphadollar I discussed this with @ooyeraju, though both of us weren't sure, as all the messages were success messages, we agreed with different shades of green. But, later I found the readability to be questionable, so I just changed the `reset` & `changes saved` to info alert (bootstrap).

I think it looks good,and the message problem is solved which was the priority. These are the screenshots of the same:
changes_saved
reset
credentials_saved

**Comment by thealphadollar** [comment]
Oh! This is so cool and looks really polished. Thanks for the aesthetic work, Sahil! 

I was just wondering if it would be better to have a "red" shade for reset message... what do you think?

**Comment by sahil-shubham** [comment]
> what do you think?

I think it's better than blue, but I aslo tried yellow as it's more of a warning. Let me know what you think: 

alert-warning
alert-danger

**Comment by thealphadollar** [comment]
> EDIT: It seems that I read your comment incorrectly, what do you mean by "shade"?

By shade, I meant anything that could represent close to "red", sort of the warning.

>  but I aslo tried yellow as it's more of a warning

I really like the yellow one, thanks @sahil-shubham for coming up with it!

**Comment by sahil-shubham** [comment]
@thealphadollar Thanks for letting me know, I have pushed the yellow the colour.

**Comment by thealphadollar** [comment]
@rakaar Would you be able find sometime to review this PR, please?

File: popup.js [hunk 1]
```diff
@@ -36,6 +36,17 @@ $("#ERPLoginID").blur(function() {
   }
 });
 
+
+function show_open_if_already_saved() {
+  chrome.storage.sync.get(results => {
+    chrome.extension.getBackgroundPage().console.log("results are  ", results);
```
Comment (thealphadollar) [inline popup.js:42]: Do you think we can remove/comment this? I believe this is just for logging and checking in personal debugging right?

Comment (sahil-shubham) [reply popup.js:42]: Yes, it's okay to comment it out. Didn't notice that, thanks.

**Review by thealphadollar — APPROVED** [review]
This looks dope and super cool!

File: popup.js [hunk 2]
```diff
@@ -36,6 +36,17 @@ $("#ERPLoginID").blur(function() {
   }
 });
 
+
+function show_open_if_already_saved() {
+  chrome.storage.sync.get(results => {
+    // chrome.extension.getBackgroundPage().console.log("results are  ", results);
```
Comment (rakaar) [inline popup.js:42]: this comment can be removed right?

**Review by rakaar — CHANGES_REQUESTED** [review]
I have checked it on my browser
Works well 

Awesome @sahil-shubham !
The new design is really great!

File: popup.js (hunk 2 above)
Comment (sahil-shubham) [reply popup.js]: Yeah, I have deleted it now. Thanks.

By the way, why is it preferred to remove code rather than commenting it out in a case like this?

Comment (rakaar) [reply popup.js]: when i added the function `show_open_if_already_saved` i put that line for debugging purpose, but hadn't removed it
it was my fault actually

i realized after i ran [git blame](https://github.com/metakgp/erp-auto-login/blame/6594487a5bfe11d65784d9dab52f6f4cd0a8186e/popup.js#L76) and checked that

**Review by rakaar — APPROVED** [review]

File: popup.js (hunk 2 above)
Comment (thealphadollar) [reply popup.js]: > why is it preferred to remove code rather than commenting it out in a case like this?

This is a beautiful question Sahil. In a concise manner, the reason is that it can be confusing to others who work on the project as to why the piece of code is commented out (this is called noise).

Please read more on this here, https://www.nayuki.io/page/dont-share-commented-out-code

**Comment by thealphadollar** [comment]
@rakaar Thank you very much for your review, it helped fast track and have double verification of the working.

@sahil-shubham Thank you working on this aesthetic fix and contributing to make ERP Auto Login look good 🔥🔥

**Review by thealphadollar — APPROVED** [review]
